In [ ]:
import numpy as np 

##1d - 
##2d -[[]]
##

In [ ]:
##creating arrays
# lst = [1,2,3,4]
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [4]:
##arange
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
## ones
# arr3 = np.ones(6)
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4 = np.linspace(1,10,20)
arr4 

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [11]:
##2d array -- matrix -- m x n 

##reshape 

arr5 = np.arange(1,31).reshape(6,5)
arr5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
##
arr6 = np.random.randint(1,10,(2,6))
arr6

array([[2, 4, 7, 1, 6, 3],
       [2, 4, 7, 2, 2, 2]], dtype=int32)

In [15]:
arr7 = np.arange(60).reshape((12,5))
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [19]:
arr7.shape
arr7.dtype
arr7.ndim
arr7.size

60

In [20]:
arr7.flatten()
arr7.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [21]:
arr8 = arr7.T
arr8.shape

(5, 12)

In [22]:
##accessing and slicing in arrays

##1d array --simple list 
arr8 = np.arange(10)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr8[1:5]

array([1, 2, 3, 4])

In [26]:
arr8[6] = 600
arr8

array([  0,   1,   2,   3,   4,   5, 600,   7,   8,   9])

In [27]:
##2d array -- [row start:row end:row skip,columns start:stop:skip ]
arr7 = np.arange(60).reshape((12,5))
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [41]:
arr7[::-1,::-1]

array([[59, 58, 57, 56, 55],
       [54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45],
       [44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35],
       [34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [34]:
##creating 3d array 
arr = np.random.randint(1,10,(2,3,5))
arr

array([[[2, 7, 5, 5, 4],
        [7, 4, 6, 6, 1],
        [4, 9, 6, 1, 8]],

       [[1, 5, 2, 1, 8],
        [9, 4, 2, 2, 7],
        [4, 6, 5, 1, 3]]], dtype=int32)

In [ ]:
arr = np.arange(225).reshape(3,15,5)
arr         #[2,77,152]

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [37]:
##3d array --[table start:end:skip,row start:end:skip,columns start:end:skip]

arr[0:2,0:6,0:3]

array([[[  0,   1,   2],
        [  5,   6,   7],
        [ 10,  11,  12],
        [ 15,  16,  17],
        [ 20,  21,  22],
        [ 25,  26,  27]],

       [[ 75,  76,  77],
        [ 80,  81,  82],
        [ 85,  86,  87],
        [ 90,  91,  92],
        [ 95,  96,  97],
        [100, 101, 102]]])